### ISSUE TITLE
Change license to Mozilla public license version 2 for Linux kernel compatibility

### ISSUE THREAD

**Issue by natewrench** [nuta/kerla#111] opened 2021-12-05 03:07 UTC
Hi I was wondering if you could change the license to the Mozilla public license version 2 that way it has compatibility for the Linux kernel which is under GPl version 2 only and Apache license isn't compatible with the GPl version 2

**Comment by nuta** [comment] 2021-12-05 09:38
Duplicate of #5. Please follow the discussion happened in that issue.

**Closed by nuta** 2021-12-05 09:39 UTC
Labels: Resolution: Duplicate
