### ISSUE TITLE
Maybe change the license is good choice (such as GPLv3)

### ISSUE THREAD

**Issue by mdtrooper** [nuta/kerla#5] opened 2021-10-26 11:48 UTC
The big problem of MIT license is that the companies love take the project and close it or not colaborate in the main or parent project. Because MIT license has not the *"Freedom 3: The freedom to improve the program, and release your improvements (and modified versions in general) to the public, so that the whole community benefits."* .

There are a lot of links about this:
 - https://www.lesinskis.com/MIT-licence-community-hostile.html
 - https://www.gnu.org/philosophy/open-source-misses-the-point.en.html
 - https://www.quora.com/What-are-the-key-differences-between-the-GNU-General-Public-license-and-the-MIT-License

IMHO: GPLv3 is better.

**Comment by vorot93** [comment] 2021-10-30 02:34
I see the largest argument for GPL is that 'evil companies may stash away changes to my precious source code'. The answer depends on how active the project is.

If you are a strong upstream, and treat contributors well, the _last_ thing an enterprise needs is thousands of man-hours spent on merging changes into their private fork, when they could be working on their products instead. Instead, top devs are _hired_ by the big giants to be key upstream contributors, because it's the path of least resistance for everyone involved.

This is of course not true if you are a feeble upstream with little to no recent commit count. But if the project is so dead then 'evil companies' can just rewrite the whole thing. So the benefit of GPL is dubious here as well.

I feel Kerla will be a strong upstream. And if you _eventually_ want to see full-time contributors, then permissive licensing is a no-brainer. For all my projects I use Apache-2.0.

**Comment by Zambito1** [comment] 2021-11-01 14:04
@michalfita 
> during my 20 years professional programming career I've never written software running on someone's computer

Then you (or your employers) have been shooting yourself (/themselves) in the foot by avoiding GPL software. The GPL only activates when you distribute the software to others. If you are only running the software you write on your own computers, permissive licenses behave exactly the same as the GPL. However, the fact that you bring up tivoization prevention as a negative in this context makes me believe you think you own the computers after you sell them to your customer. I think this highlights exactly why permissive licenses should be avoided. Once you sell a computer, it is no longer your computer.

@vorot93 

> I see the largest argument for GPL is that 'evil companies may stash away changes to my precious source code'.

I hope you didn't get that from me. I don't care if anyone keeps changes to themselves; nor does the GPL. What I care about is having control over my own computer. The biggest reason to prefer a permissive license over a copyleft license, is for compatibility with a proprietary license. Proprietary licenses are antithetical to "control over my own computers".

The GPL allows for proprietary forks, believe it or not. Companies are free to take GPL code, make changes, use it, and not tell anyone. What the GPL does not allow is the *distribution* of proprietary forks, so long as they remain proprietary. I think the distribution of proprietary forks would be unjust, because the proprietor would have more permission over the end users machine (in this case, at a **kernel** level), that they do not own.

**Comment by inoshy** [comment] 2021-11-01 15:15
Why would you want so much control? If you wanted full control you wouldn't make softwares open source in the first place - because that would wide open the gate of forks, modification and distribution by others, that may or may not be approved by you.

**Comment by DodyAlkarkhi** [comment] 2021-11-01 17:19
> Why would you want so much control?

Because it's our computers?

>If you wanted full control you wouldn't make softwares open source in the first place - because that would wide open the gate of forks, modification and distribution by others, that may or may not be approved by you.

You do realise there is something called disassembly?

Also let me remind everyone that this is a guy that just wants to steal the code without contributing anything back because apparently the only way to make money is through stealing open source and make it proprietary. Like if you're a diehard proprietary software fan then write your own software from scratch.

And now that I realise, he deleted the comment lol. Good thing I quoted it. Here it is:

>  I want to use this in my papiatary project to make some money with it. I have a family, and I need to provide them with food. and food is far from free where I live.

**Comment by Zambito1** [comment] 2021-11-01 17:20
@inoshy 

> Why would you want so much control?

I want to control my computer because I paid for it. You have to try to not understand that.

> If you wanted full control you wouldn't make softwares open source in the first place - because that would wide open the gate of forks, modification and distribution by others, that may or may not be approved by you.

By making it "open source", it's already been approved. I don't care to control what other people do with their own computers. That's not my business, nor should it be yours.

**Comment by inoshy** [comment] 2021-11-01 17:29
> Also let me remind everyone that this is a guy that just wants to steal the code without contributing anything back because apparently the only way to make money is through stealing open source and make it proprietary. Like if you're a diehard 
@DodyAlkarkhi 
Lmaoooo, you got triggered!
Whats your business with that, if I steal the code? Or you just scratching in ache that I will make some money and you won't? 
You remind me of 12y/o :) no offense, but it is how it is :v

**Comment by DodyAlkarkhi** [comment] 2021-11-01 17:31
@inoshy

Thats really ironic. i'm just stating facts. You on the other hand react to facts like a 4y/o

**Comment by inoshy** [comment] 2021-11-01 17:31
> > I want to use this in my papiatary project to make some money with it. I have a family, and I need to provide them with food. and food is far from free where I live.

@DodyAlkarkhi 
Hmm, I dont remember that comment was from me? You are just falsely accusing me because you failed to convince nuta to license under gpl :v I know right?

**Comment by DodyAlkarkhi** [comment] 2021-11-01 17:34
> > > I want to use this in my papiatary project to make some money with it. I have a family, and I need to provide them with food. and food is far from free where I live.
> 
> @DodyAlkarkhi Hmm, I dont remember that comment was from me? You are just falsely accusing me because you failed to convince nuta to license under gpl :v I know right?

There's a reason you deleted it lol. I knew you were going to come up with that excuse

**Comment by inoshy** [comment] 2021-11-01 17:34
> @inoshy
> 
> Thats really ironic. i'm just stating facts. You on the other hand react to facts like a 4y/o
@DodyAlkarkhi 
Hmm, I think a 4 y/o can barely walk, let alone type. But a 12 y/o can certainly type something and the proof is you!

**Comment by inoshy** [comment] 2021-11-01 17:35
> > > > I want to use this in my papiatary project to make some money with it. I have a family, and I need to provide them with food. and food is far from free where I live.
> > 
> > 
> > @DodyAlkarkhi Hmm, I dont remember that comment was from me? You are just falsely accusing me because you failed to convince nuta to license under gpl :v I know right?
> 
> There's a reason you deleted it lol. I knew you were going to come up with that excuse

You are falsely accusing me because you failed to convince nuta :)

**Comment by DodyAlkarkhi** [comment] 2021-11-01 17:36
> > @inoshy
> > Thats really ironic. i'm just stating facts. You on the other hand react to facts like a 4y/o
> 
> @DodyAlkarkhi Hmm, I think a 4 y/o can barely walk, let alone type. But a 12 y/o can certainly type something and the proof is you!

I'm talking about your reasoning "You're jealous i make money and you don't". Exactly how a 4y/o would react

**Comment by DodyAlkarkhi** [comment] 2021-11-01 17:39
> > > > @inoshy
> > > > Thats really ironic. i'm just stating facts. You on the other hand react to facts like a 4y/o
> > > 
> > > 
> > > @DodyAlkarkhi Hmm, I think a 4 y/o can barely walk, let alone type. But a 12 y/o can certainly type something and the proof is you!
> > 
> > 
> > I'm talking about your reasoning "You're jealous i make money and you don't". Exactly how a 4y/o would react
> 
> I don't think 4y/o reacts to such complex things (monetization from software) but a 9y/o would certainly do! (proof: you)

I love how you instantly change the topic when I quote your reasoning for wanting a permissive license. Then you accuse me of lying and then go to your 4y/o insults.

**Comment by inoshy** [comment] 2021-11-01 17:40
> I love how you instantly change the topic when I quote your reasoning for wanting a permissive license. Then you accuse me of lying and then go to your 4y/o insults.

Thats because you are a plain liar! you are accusing me of things that I didn't do :v
And obviously you are 9. not more, not less.

**Comment by DodyAlkarkhi** [comment] 2021-11-01 17:42
> > I love how you instantly change the topic when I quote your reasoning for wanting a permissive license. Then you accuse me of lying and then go to your 4y/o insults.
> 
> Thats because you are a plain liar! you are accusing me of things that I didn't do :v And obviously you are 9. not more, not less.

lol ask @mdtrooper  and @kleinph. We know your company wont last long when we expose your github history to your customers

**Comment by DodyAlkarkhi** [comment] 2021-11-01 17:46
> > lol ask @mdtrooper and @kleinph. We know your company wont last long when we expose your github history to your customers
> 
> Who are they? I don't know any of these pieces. And I am not accountable for anything that I didn't say. You are straight up making stuffs and accusing me.

they were the ones upvoting me and downvoting you. You straight up lie and claim you're innocent. It doesn't take long to realise who I were talking to in the comments. You deleting the comment straight after makes it even more suspicious.

**Comment by inoshy** [comment] 2021-11-01 17:48
> they were the ones upvoting me and downvoting you. You straight up lie and claim you're innocent. It doesn't take long to realise who I were talking to in the comments. You deleting the comment straight after makes it even more suspicious.

What comments? delete what? What I know is you are trying to falsely accuse me. And I dont mind downvotes. I am open about my opinions.

**Comment by DodyAlkarkhi** [comment] 2021-11-01 17:52
> > they were the ones upvoting me and downvoting you. You straight up lie and claim you're innocent. It doesn't take long to realise who I were talking to in the comments. You deleting the comment straight after makes it even more suspicious.
> 
> What comments? delete what? What I know is you are trying to falsely accuse me. And I dont mind downvotes. I am open about my opinions.

Again you're going on circles. I don't have the comment since you deleted it but it doesn't take long to realise who I were talking to here:

![Screenshot_20211101_175035](https://user-images.githubusercontent.com/38881427/139717102-2834b7d1-56fd-4776-a0c7-da9a6749fe5e.png)

...

![Screenshot_20211101_174935](https://user-images.githubusercontent.com/38881427/139717136-85931d45-e41d-49a9-9afa-5df37b8f56f3.png)

**Comment by inoshy** [comment] 2021-11-01 17:53
MIT all the ay - thats a very good comment. Thanks you brought it up. MIT license makes my day.

**Comment by DodyAlkarkhi** [comment] 2021-11-01 17:54
And you purposefully ignore the second screenshot? Yeah keep denying

**Comment by inoshy** [comment] 2021-11-01 17:56
> And you purposefully ignore the second screenshot? Yeah keep denying

deny what? I am not denying you are falsely accusing me. I don't deny the truth. I am not afraid what happens when I embrace the truth. The truth is, you are trying to play a game, to keep me away from free software movement. That wont happen. I will keep on my campaign for free software and FOSS licenses.

**Comment by DodyAlkarkhi** [comment] 2021-11-01 17:56
what?

**Comment by inoshy** [comment] 2021-11-01 17:57
yep.

**Comment by DodyAlkarkhi** [comment] 2021-11-01 17:57
Could you be more clear since your comment seems like some kind of damage control lol

**Comment by inoshy** [comment] 2021-11-01 17:58
> Could you be more clear since your comment seems like some kind of damage control lol

Read it again and again, like a for loop ;-)

**Comment by DodyAlkarkhi** [comment] 2021-11-01 18:03
How am I keeping you away from the free software movement? You do realise the founder of the free software movement wrote the GPL, right? And they also call permissive licenses "pushover licenses".

And what about wanting to steal the source code for your "proprietary project"? Thats most anti free software movement you can get. Or maybe I missed that you changed your mind somewhere :)

**Comment by inoshy** [comment] 2021-11-01 18:06
> And what about wanting to steal the source code for your "proprietary project"? Thats most anti free software movement you can get. Or maybe I missed that you changed your mind somewhere :)

Who wrote gpl? I dont know. I dont recognize them. dont bother me with these bs. and dont try to accuse me. I am tired of people's drama, when they fail to convince people with their pet license, then get triggered, and then stright up make stuffs and accuses free software community.

**Comment by vorot93** [comment] 2021-11-02 06:19
@Zambito1 

> What I care about is having control over my own computer. The biggest reason to prefer a permissive license over a copyleft license, is for compatibility with a proprietary license. Proprietary licenses are antithetical to "control over my own computers".

More often than not, software is _not_ written for your PC. @michalfita has made an excellent outline of where the software industry is at, and why GPL is avoided like wildfire. Besides, many companies simply don't want to have their IP infected by and subordinated to legal text copyrighted and controlled by one American non-profit.

When it comes to your personal crusade for freeing your PC, you can use and improve software under GPL all the way you want. Others don't have to suffer because of it.

> The GPL allows for proprietary forks, believe it or not. Companies are free to take GPL code, make changes, use it, and not tell anyone. What the GPL does not allow is the _distribution_ of proprietary forks, so long as they remain proprietary. I think the distribution of proprietary forks would be unjust, because the proprietor would have more permission over the end users machine (in this case, at a **kernel** level), that they do not own.

Hold on right there, you're jumping between two different topics. What those companies do is their matter. It's not like they are forcing _you_ to install their proprietary forks, are they? You can compile any free kernel yourself and use it.

**Comment by inoshy** [comment] 2021-11-02 07:43
> More often than not, software is _not_ written for your PC. @michalfita has made an excellent outline of where the software industry is at, and why GPL is avoided like wildfire. Besides, many companies simply don't want to have their IP infected by and subordinated to legal text copyrighted and controlled by one American non-profit.

This.

**Comment by inoshy** [comment] 2021-11-02 08:11
Guys Jacpot51 downvoted the proposal to change the license! Can't believe. Those who don't know jackpot51, he is the creator of Redox OS.

**Fools rush in where angels fear to tread.**

**Comment by nuta** [comment] 2021-11-02 08:21
Everyone, please read [Rust's Code of Conduct](https://www.rust-lang.org/policies/code-of-conduct), which [will be used in Kerla](https://github.com/nuta/kerla/pull/38) as well, before discussing the software license here.

This thread tends to be too heated. Even if you think an opinion is incorrect or does not make sense to you, there is no need to be rude and offensive. There's no perfect software license. Each license has pros and cons. Don't forget to **respect that people have differences of opinion**.

**Comment by michalfita** [comment] 2021-11-02 11:08
> Then you (or your employers) have been shooting yourself (/themselves) in the foot by avoiding GPL software. The GPL only activates when you distribute the software to others.

@vorot93 made excellent comment already, but I'd like to underscore one thing you @Zambito1 misread: Companies avoid GPLv3 licence code in products **exposed to customers**, not avoid using it at all. `gdb` is good example... however there's growing interest `lldb`.

> However, the fact that you bring up tivoization prevention as a negative in this context makes me believe you think you own the computers after you sell them to your customer.

Fallacy. You @Zambito1 as a crusader perceive computers through the prism of personal ownership. Again, you miss the point of law and regulations, but if you don't like the product where firmware cannot be replaced by your own you don't have to buy it - you can cook your own solutions on Raspberry Pi (btw. they're using proprietary blobs licensed by Broadcom). Another aspect is who the customer is - many products I worked on where never sold to private customers, only companies - they don't have doubts and as long as money buys them support they expected they don't mind proprietary code and locked bootloaders.

> Once you sell a computer, it is no longer your computer.

True. But we very rarely sell software, only license **to use it**. And I may sell license to source code if I wish (it's actually popular practice in embedded world).

> What I care about is having control over my own computer. The biggest reason to prefer a permissive license over a copyleft license, is for compatibility with a proprietary license. Proprietary licenses are antithetical to "control over my own computers".

OK, but it's about **your** computer, 100 other customers (mostly companies) don't mind paying for license to use software they don't have freedom to modify. And this is not going to change because Stallman once said all software should be open for everyone. We can embrace open software as common good, but we still have to let programmers earn for bread and shelter... and quite often equipment to work on.

> The GPL allows for proprietary forks, believe it or not. Companies are free to take GPL code, make changes, use it, and not tell anyone. What the GPL does not allow is the distribution of proprietary forks, so long as they remain proprietary.

You're only right to certain extent. We in the past have to use network traffic sniffer with dissector for proprietary protocol which license didn't let us use outside our company. We started working on dissector for Wireshark (licensed GPLv2) when our lawyers instructed us, that using that dissector across business units in different countries classifies as distribution according to the license... so we had to pay thousands of dollars for proprietary network sniffer which let us keep the protocol confined within company. The protocol was a about 200 pages of Word document - nothing else, no code delivered with it, just the specification with explicit license to use only within boundaries of our company and certain category of products. If Wireshark had permissive licence or exception for dissectors we'd used and train 3 to 5 developers how to write dissectors for Wireshark in the process; what are chances in future one of them would use the skill to add open source dissector to Wireshark? Things like that are lost chances. There are companies out there that underlay statements to sign on employment that people would not contribute to GPL during tenure without explicit written permission from legal department - the risk of defamation if there would ever be any patent dispute is too high for them. With permissive license, in case of any suspicion patents where violated it's enough to remove the code, while GPL may imply patent had been implicitly licensed - no patent holder would like that (luckily in Europe software patents don't hold).

A lot has been said about licenses in this thread, I'm signing of myself from observing further discussion and participation as I don't have time to follow this any more. Kerla stays MIT/Apache 2.0 for now and that's fine for me.

**Comment by hobdob** [comment] 2021-11-02 21:20
@nuta I think it's time to lock this issue now (or even locking it). A lot has been said already and it's just going to be back and forth arguments.

**Comment by nuta** [comment] 2021-11-03 08:31
Closing this issue because I'm not going to change the license ***for now***. Please feel free to open a new issue when you noticed that Kerla is suffering from a free rider problem. For now, it's too early to change the license. See the comment I mentioned above:

> However, I'm going to go with Apache2.0/MIT FOR NOW. Despite permissive licenses don't require you to contribute to the upstream, I have seen a lot of companies (including my company) are upstreaming their work and don't want them not to do so because of the non-permissive license.
>
> That being said, I do understand the free-rider problem is a real threat as we've seen in our history. If Kerla run into the problem by any chance and if I realized Apache 2.0/MIT doesn't seem to work well for us anymore, I'll consider switching the software license as MongoDB did.
>
> Switching to GPL sounds too early to me. Kerla is still a a toddling baby among operating systems.

**Closed by nuta** 2021-11-03 08:31 UTC

**Comment by EuriNaiz** [comment] 2021-11-08 05:04
I am here just to suggest a GPLv3 later or AGPLv3 later license, god, Linux since a lot is GPLv2 only, it's a opportunity to fix it, I'll be happy using Kerla it it will have the best license, but god... MIT? wtf? Its a really bad idea create a kernel to substitute linux but without the libre software guaranties, I'm sure that if this grow up so much, the corps will take it and make business without any important and just contribution, how happened before with PlaystationOS or MacOS and FreeBSD.

And the only way to avoid the tivoization and bootloader blocking in android phones is the GPLv3. So, Docker its becoming so popular in these last years, Personally i consider the best license option is APGLv3 later.

**Comment by inoshy** [comment] 2021-11-08 08:55
@EuriNaiz MIT is the best license. gpl is freedom restricting. Embrace MIT, reject GPL.

**Comment by inoshy** [comment] 2021-11-08 08:59
@EuriNaiz MIT is the best license. gpl is freedom restricting.
If you think @nuta  made a mistake choosing MIT, write your own kerla and don't whine after long been the issue is closed and decission has been taken.

**Comment by EuriNaiz** [comment] 2021-11-08 21:46
The GPL does not restrict freedom, it guarantees it.

**Comment by inoshy** [comment] 2021-11-08 23:45
> The GPL does not restrict freedom, it guarantees it.

gpl is not a good license. it's a nightmare of a old school license. it's not 1936 anymore.

**Comment by EuriNaiz** [comment] 2021-11-08 23:50
You're so ignorant, GPLv3 were introduced in Jun 2007 to fix the new problems like tivoization, the privative SaaS and other disgusting things.

Please, read before to talk/write about something you do not know.

**Comment by inoshy** [comment] 2021-11-08 23:58
> You're so ignorant,
@EuriNaiz That would be you 🤣 If you think nuta made mistake, write your own kerla and don't whine like a kid 🤣

**Comment by inoshy** [comment] 2021-11-09 00:00
> You're so ignorant

@EuriNaiz That would be you. If you think nuta made mistake, write your own kerla and don't whine 🤣

**Comment by EuriNaiz** [comment] 2021-11-09 00:30
@inoshy OMG what's wrong in your life? I haven't got time to read the whole thread but... definitely you're so ignorant and just a troll.

If you wont say something useful, don't do it, there is not necessity to insult or say stupid and child things like "iS hIs CoDe, iF wRitE tHe YoUrS".

Please, don't reply me, just keep quiet, If you have got some interesting to contribute, you're welcome, if not, I do not wanna see it, just don't reply me or quote me.
I'm here to discuss this problem and try to search a solution, not to insult or be insulted by a random guy that needs to insult the other people and support his own comments (because the others don't) just to be fine with himself just for a moment.

**Comment by nuta** [comment] 2021-11-09 00:59
@inoshy @EuriNaiz Please follow our [Code of Conduct](https://github.com/nuta/kerla/blob/main/CODE_OF_CONDUCT.md). Please be kind and courteous.

As I said earlier, I think it's still not a good time to change license. I do know what copyleft licenses provide and their advantages, furthermore it’s not like I stick to permissive licenses. However, they're risky since they would prevent companies from using (and contributing to) Kerla just because of the non-permissive license.

As @EuriNaiz said, it's also true that some companies are using open source softwares without contribution. I do recognize the concern is a real threat. If we notice the unfortunate situation, let's discuss the copyleft license to deal with the situation then.

Switching to GPL sounds too early to me. Kerla is still a toy operating system.

**Comment by nuta** [comment] 2021-11-09 01:25
I'll lock the conversation since we're repeating the same conversation over and over. Please feel free to create a new issue ***only if*** you noticed that we're suffering from the free-rider problem. I'm happy to discuss non-permissive licenses then.

**Comment by lain-dono** [comment] 2021-11-09 01:25
@nuta I would suggest moving it to discussions.

- Perhaps you would like to use the GPL?
- No, I choose MIT/Apache.
- OK.

Anything beyond that is just a discussion about licenses.

**Comment by nuta** [comment] 2021-11-09 01:33
@lain-dono I think Kerla's discussion forum is not a good place to discuss about the license. We'll repeat the same conversation there too. More importantly, general discussions on software licenses are not specific to Kerla as we've seen in this thread.
